DROP DATABASE IF EXISTS `OwbManagerDb`;
CREATE DATABASE `OwbManagerDb`;
USE `OwbManagerDb`;

CREATE TABLE `OwbMeeting` (
    `id` INT(11) AUTO_INCREMENT NOT NULL,
    `mid` VARCHAR(255) NOT NULL,
    `cuser` VARCHAR(255) NOT NULL,
    `ctime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `status` INT(11) NOT NULL DEFAULT 0,
    `machine`VARCHAR(255),
    PRIMARY KEY(`id`)
)ENGINE = INNODB, DEFAULT CHARSET = UTF8;

CREATE TABLE `OwbMachine` (
    `mname` VARCHAR(255) NOT NULL,
    `ip` VARCHAR(255) NOT NULL,
    `port` INT(11) NOT NULL,
    `status` INT(11) NOT NULL DEFAULT 0,
    `hbtime` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`mname`)
)ENGINE = INNODB, DEFAULT CHARSET = UTF8;
